name: Test Dependencies And Errors (Linux)

on: [pull_request, push]
jobs:
  Check-Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}
      - run: python3 -m venv ./
      - run: source ./bin/activate
      - run: pip install -r requirements.txt
      - run: python3 -m py_compile ./src/main.py
      
