name: Test Dependencies And Errors (Windows)

on: [pull_request, push]
jobs:
  Check-Dependencies:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: cd ${{ github.workspace }}
      - run: python -m venv .\
      - run: .\scripts\activate.ps1
      - run: pip install -r requirements.txt
      - run: python -m py_compile .\src\main.py
      
